spring:
  application:
    name: taskManagement

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5433/taskManager
    username: postgres
    password: postgres

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

  mail:
    host: smtp.mail.ru
    port: 587
    username: danil.yudin
    password: danil.yudin
    properties:
      mail:
        smtp:
          auth: true
          starttls.enable: true


  http:
    logging:
      enabled: true
      logLevel: DEBUG
